### ISSUE TITLE
macworld.com links not clickable (main page loads ok)

### ISSUE THREAD

**Issue by garvankeeley** [SergeyZhukovsky/tracking-protection#5]
http://www.macworld.com loads, but the links on the page are blocked by TP

**Comment by SergeyZhukovsky** [comment]
Everything because of that resource
pcworldcommunication.d2.sc.omtrdc.net
When I put it to white list, the website works well. The strange thing also that diconnect plugin for Chrome  and Firefox shows that it blocks that resource also.

**Comment by bbondy** [comment]
But they load the page correctly?
That doesn't make sense if they do block but display correctly, I think someone else is going on.

**Comment by bbondy** [comment]
After investigating this more it's because of blocking 4 images at:
`pcworldcommunication.d2.sc.omtrdc.net` and `b.scorecardresearch.com`

I noticed that disconnect redirects to about:blank for resources. 
And it provides a 1px transparent png for images instead of blocking: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==

I haven't found a need to do redirecting to about:blank, but doing the 1px transparent png image does fix things.

**Comment by SergeyZhukovsky** [comment]
It was fixed by inserting 1px transparent image.
