### ISSUE TITLE
iOS crash: FirstPartyHost.h line 110 ST_FIRST_PARTY_HOST::deserialize(char*, unsigned int)

### ISSUE THREAD

**Issue by garvankeeley** [SergeyZhukovsky/tracking-protection#9]
https://fabric.io/brave6/ios/apps/com.brave.ios.browser/issues/56ce8da0f5d3a7f76b164b44

6 crashes for 6 users, low incidence, low reproducibility

**Comment by SergeyZhukovsky** [comment]
@garvankeeley do you have a check on correct file downloaded? The reason I ask is because I had the same problems in Android(random crashes in native libs). And I found it is because of they were downloaded incorrectly(sizes of original file and downloaded were not equal). That is why I added a check if downloaded size is not the same as in the server(using content-length HTTP property) I assume the file is wrong. And also for old users I made a check on length with etag with that.

**Comment by garvankeeley** [comment]
No need to check I don't think, on network error, the file is not used, and file downloaded uses an 'atomic' file move operation from the temp download destination to the final one. 
Moreover, if there was a corrupt file, this crash would repeat for this user, and we see the crash happening only once per user.

**Comment by SergeyZhukovsky** [comment]
@garvankeeley the crash could happen randomly sometimes because RAM image is not consistent and it depends on what it is in the current address what we want to reach. It is like uninitialized variable: you never knew what value is there.

**Comment by SergeyZhukovsky** [comment]
@garvankeeley I think it is the same issue as here
https://github.com/SergeyZhukovsky/tracking-protection/issues/13
I just fixed 2 places with memory corruption, please grab new cpp files from that lib on a new build. There was one problem in a .dat file also, we will just replace it and it will be redownloaded.
